kalite/control_panel/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(__package__ + '.views',
    # Zone
    url(r'zone/(?P<zone_id>\w+)/$', 'zone_management', {}, 'zone_management'),
    url(r'zone/(?P<zone_id>\w+)/edit$', 'zone_form', {}, 'zone_form'),

    # Device
    url(r'zone/(?P<zone_id>\w+)/device/(?P<device_id>\w+)/$', 'device_management', {}, 'device_management'),

    # Facility
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/edit$', 'facility_form', {}, 'facility_form'),
    url(r'zone/(?P<zone_id>\w+)/facility/new/$', 'facility_form', {"facility_id": "new"}, 'add_facility'),
    url(r'facility/(?P<facility_id>\w+)/edit/$', 'facility_form', {}, 'facility_form'),
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/management/$', 'facility_management', {}, 'facility_management'),
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/management/group/(?P<group_id>\w+)/$', 'facility_management', {}, 'group_management'),

    url(r'account/$', 'account_management', {}, 'account_management'),
    url(r'export/$', 'data_export', {}, 'data_export'),    
)

kalite/distributed/urls.py
"""
URLS for constructing the KA Lite app. Mostly imported from other apps.
Notable urls include:
* serving media and static files.  This can be overriden by putting a (fast) front-end server
    (like nginx) to speed things up.
* The "splat" handler, which catches all uncaught requests, and tries to turn them into a
    node in the topic tree.
"""
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

from . import api_urls
import kalite.dynamic_assets.urls
import kalite.coachreports.urls
import kalite.control_panel.urls
import kalite.facility.urls
import kalite.updates.urls
import securesync.urls

from kalite.contentload import settings as contentload_settings

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^images/.*$', lambda request: HttpResponseRedirect(settings.STATIC_URL[:-1] + request.path)),
    url(r'^favico.ico/?$', lambda request: HttpResponseRedirect(settings.STATIC_URL + "images/distributed/" + request.path)),
)


urlpatterns += patterns('',
    url(r'^securesync/', include(kalite.facility.urls)),  # for backwards compat
    url(r'^securesync/', include(securesync.urls)),
)


# TODO: This should only be in DEBUG settings and the HTTP server should be
# serving it otherwise. Cherrypy is currently serving it through modifications
# in kalite/distributed/cherrypyserver.py
urlpatterns += patterns('',
    url(r'^%skhan/(?P<path>.*)$' % settings.CONTENT_URL[1:], 'django.views.static.serve', {
        'document_root': contentload_settings.KHAN_ASSESSMENT_ITEM_ROOT,
    }),
    url(r'^%s(?P<path>.*)$' % settings.CONTENT_URL[1:], 'django.views.static.serve', {
        'document_root': settings.CONTENT_ROOT,
    }),
    url(r'^%s(?P<path>.*)$' % settings.CONTENT_DATA_URL[1:], 'django.views.static.serve', {
        'document_root': settings.CONTENT_DATA_PATH,
    }),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

# Teaching / admin patterns
urlpatterns += patterns(__package__ + '.views',
    # For teachers
    url(r'^coachreports/', include(kalite.coachreports.urls)),

    # For admins
    url(r'^update/', include(kalite.updates.urls)),

    url(r'^help/$', 'help', {}, 'help'),

    # API
    url(r'^api/', include(api_urls)),

    # Management: Zone, facility, device
    url(r'^management/zone/$', 'zone_redirect', {}, 'zone_redirect'),  # only one zone, so make an easy way to access it
    url(r'^management/device/$', 'device_redirect', {}, 'device_redirect'),  # only one device, so make an easy way to access it
    url(r'^management/', include(kalite.control_panel.urls)),  # no org_id, but parameter needed for reverse url look-up
)

# Dynamic assets
urlpatterns += patterns('',
    url(r'^_generated/', include(kalite.dynamic_assets.urls)),
)

# Testing
if "kalite.testing.loadtesting" in settings.INSTALLED_APPS:
    urlpatterns += patterns(__package__ + '.views',
        url(r'^loadtesting/', include('kalite.testing.loadtesting.urls')),
    )

# Front-end
urlpatterns += patterns(__package__ + '.views',
    url(r'^$', 'homepage', {}, 'homepage'),
    url(r'^search/$', 'search', {}, 'search'),
    # the following pattern is a catch-all, so keep it last:

    # Allows remote admin of the distributed server
    url(r'^cryptologin/$', 'crypto_login', {}, 'crypto_login'),

    # the following has no "$", and thus catches anything starting with "learn/"
    url(r'^learn/', 'learn', {}, 'learn'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
    )

handler403 = __package__ + '.views.handler_403'
handler404 = __package__ + '.views.handler_404'
handler500 = __package__ + '.views.handler_500'

kalite/facility/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

from . import api_urls


urlpatterns = patterns(__package__ + '.views',
    url(r'^teacher/$', 'add_facility_teacher', {},'add_facility_teacher'),
    url(r'^student/$', 'add_facility_student', {}, 'add_facility_student'),
    url(r'^signup/$', 'facility_user_signup', {}, 'facility_user_signup'),
    url(r'^user/(?P<facility_user_id>\w+)/edit/$', 'edit_facility_user', {}, 'edit_facility_user'),

    url(r'^group/$', 'group_edit', {'group_id': 'new'}, 'add_group'),
    url(r'^group/(?P<group_id>\w+)/edit/$', 'group_edit', {'facility': None}, 'group_edit'),

   
)

urlpatterns += patterns(__package__ + '.api_views',
    url(r'^api/', include(api_urls)),
)

kalite/updates/urls.py
from django.conf.urls import patterns, url
from django.conf import settings


urlpatterns = patterns(__package__ + '.views',
    url(r'^videos/$', 'update_videos', {}, 'update_videos'),
    url(r'^languages/$', 'update_languages', {}, 'update_languages')

)

python-packages/securesync/devices/models.py
"""
"""
import datetime
import logging
import uuid
from annoying.functions import get_object_or_None

from django.conf import settings
from django.contrib.auth.models import check_password
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction, IntegrityError
from django.db.models import Q
from django.db.models.expressions import F
from django.utils.text import compress_string
from django.utils.translation import ugettext_lazy as _

from .. import ID_MAX_LENGTH, IP_MAX_LENGTH, VERSION
from .. import crypto
from ..engine.models import SyncedModel, SyncedModelManager
from fle_utils.general import get_host_name
from fle_utils.django_utils.debugging import validate_via_booleans
from fle_utils.django_utils.classes import ExtendedModel


class RegisteredDevicePublicKey(ExtendedModel):
    public_key = models.CharField(max_length=500, help_text="(This field will be filled in automatically)")
    zone = models.ForeignKey("Zone")
    created_timestamp = models.DateTimeField(auto_now_add=True, null=True, default=None)  # Null for oldies
    used_timestamp = models.DateTimeField(null=True, default=None)

    class Meta:
        app_label = "securesync"

    def __unicode__(self):
        out_str = u"%s... (Zone: %s)" % (self.public_key[0:5], self.zone)
        out_str += (u"; created on %s" % self.created_timestamp) if self.created_timestamp else ""
        out_str += (u"; used on %s" % self.used_timestamp) if self.used_timestamp else ""
        return out_str

    def use(self):
        # Never should get called if timestamp
        assert not self.used_timestamp, "Cannot reuse public key registrations"
        self.used_timestamp = datetime.datetime.now()
        self.save()

    def is_used(self):
        return self.used_timestamp is not None


class UnregisteredDevice(ExtendedModel):
    """
    Bare list of all unregistered devices that 'ping' us with a device ID
    """
    id = models.CharField(primary_key=True, max_length=ID_MAX_LENGTH, editable=False)


class UnregisteredDevicePing(ExtendedModel):
    """
    Whenever we receive a session request from an unregistered device,
    we increase our counter
    """
    device = models.ForeignKey("UnregisteredDevice", unique=True)
    npings = models.IntegerField(default=0)
    last_ip = models.CharField(max_length=IP_MAX_LENGTH, blank=True)
    last_ping = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"%s: %s pings, last on %s from %s" % (self.device.id, self.npings, self.last_ping, self.last_ip)

    @classmethod
    def record_ping(cls, id, ip):
        """
        We received a failed request to create a session; record that 'ping' in our DB
        """
        try:
            # Create the log (if necessary), update, and save
            # TODO: make a base class (in django_utils) that has get_or_initialize, and use that
            #   to shorten things here
            (cur_device, _) = UnregisteredDevice.objects.get_or_create(id=id)
            (cur_log, _) = cls.get_or_initialize(device=cur_device)  # get is safe, because device is unique

            cur_log.npings += 1
            cur_log.last_ip = ip
            cur_log.save()

        except Exception as e:
            # Never block functionality
            logging.error("Error recording unregistered device ping: %s" % e)


class DeviceMetadata(ExtendedModel):
    device = models.OneToOneField("Device", blank=True, null=True)
    is_trusted = models.BooleanField(default=False)
    is_own_device = models.BooleanField(default=False)
    is_demo_device = models.BooleanField(default=False)
    counter_position = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Device metadata"
        app_label = "securesync"

    def __unicode__(self):
        return u"(Device: %s)" % (self.device)


class Zone(SyncedModel):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    class Meta:
        app_label = "securesync"

    #@central_server_only  # causes circular loop, to include here
    def get_org(self):
        """
        Reverse lookup of organization containing this zone.
        """
        orgs = self.organization_set.all()
        assert orgs.count() <= 1, "Zone must be contained by 0 or 1 organization(s)."

        return orgs[0] if orgs else None

    def is_member(self, device):
        """
        """
        try:
            return ChainOfTrust(zone=self, device=device).verify()
        except:
            return False

    @validate_via_booleans
    def validate(self):
        """
        Nothing to verify--ANYBODY can make a zone.  The question is
        if you can convince anybody else to join it :P
        """
        return True

    @classmethod
    def get_headless_zones(cls):
        """
        Method for getting all zones that aren't connected to at least one organization.
        """
        # Must import inline (not in header) to avoid import loop
        return Zone.objects.filter(organization=None)

    def __unicode__(self):
        return self.name


class DeviceZone(SyncedModel):
    device = models.ForeignKey("Device", unique=True)
    zone = models.ForeignKey("Zone", db_index=True)
    revoked = models.BooleanField(default=False)
    max_counter = models.IntegerField(blank=True, null=True)

    class Meta:
        app_label = "securesync"

    @validate_via_booleans
    def validate(self):
        """
        Verify that it was created by a trusted server (old-school),
        or that it has an invitation backing the devicezone (new-school)
        """
        if self.signed_by.is_trusted():
            return True
        invitation =  get_object_or_None(ZoneInvitation, used_by=self.device, zone=self.zone)
        return self.device == self.signed_by and invitation and invitation.verify()

    def __unicode__(self):
        return u"Device: %s, assigned to Zone: %s" % (self.device, self.zone)


class DeviceManager(SyncedModelManager):

    class Meta:
        app_label = "securesync"

    def by_zone(self, zone):
        # get Devices that belong to a particular zone, or are a trusted authority
        return self.by_zones([zone.id])

    def by_zones(self, zones):
        # get Devices that belong to a list of zone IDs, or are a trusted authority
        return self.filter(Q(devicezone__zone__id__in=zones, devicezone__revoked=False) |
            Q(devicemetadata__is_trusted=True))


class Device(SyncedModel):
    name = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    public_key = models.CharField(max_length=500, db_index=True)
    version = models.CharField(max_length=len("10.10.100"), default="0.9.2", blank=True); version.minversion="0.9.3"  # default comes from knowing when this feature was implemented!

    objects = DeviceManager()
    all_objects = DeviceManager(show_deleted=True)

    key = None
    own_device = None  # cached property, shared globally.

    class Meta:
        app_label = "securesync"

    def set_key(self, key):
        assert isinstance(key, crypto.Key), "key must be a crypto Key object"
        self.public_key = key.get_public_key_string()
        self.key = key

    def get_key(self):
        if not self.key:
            try:
                if self.get_metadata().is_own_device:
                    self.key = crypto.get_own_key()
            except Device.DoesNotExist:
                # get_metadata can fail if the Device instance hasn't been persisted to the db
                pass
            if not self.key and self.public_key:
                self.key = crypto.Key(public_key_string=self.public_key)
        return self.key

    def _hashable_representation(self):
        fields = ["signed_version", "name", "description", "public_key"]
        return super(Device, self)._hashable_representation(fields=fields)

    def get_metadata(self):
        try:
            return DeviceMetadata.objects.get_or_create(device=self)[0]
        except IntegrityError as e:
            # Possible from get_or_create if the DeviceMetadata object doesn't exist
            # and the Device hasn't been persisted to the database yet.
            raise Device.DoesNotExist()

    def get_counter_position(self):
        """
        """
        if not self.id:
            return 0

        else:
            return self.get_metadata().counter_position

    def set_counter_position(self, counter_position, soft_set=False):
        metadata = self.get_metadata()
        if not metadata.device.id:  # only happens if device has not been saved yet.  Should be changed to self.id
            return

        # It's often convenient to reset the position ONLY if the new counter position
        #   is higher than the old.  So, let people be lazy--but need to send in a flag,
        #   so it's clear that something a bit unusual is happening in a "set"
        if soft_set and self.signed_by.get_counter_position() >= counter_position:
            return

        assert counter_position >= metadata.counter_position, "You should not be setting the counter position to a number lower than its current value!"
        metadata.counter_position = counter_position
        metadata.save()

    @transaction.commit_on_success
    def increment_counter_position(self):
        """Increment and return the counter position for this device.
        TODO-BLOCKER(jamalex): While from testing, this new version seems much less prone to race conditions,
        it still seems like a possibility. Further testing would be good.
        """
        metadata = self.get_metadata()
        metadata.counter_position = F("counter_position") + 1
        metadata.save()
        return self.get_metadata().counter_position

    def full_clean(self, *args, **kwargs):
        # TODO(jamalex): we skip out here, because otherwise self-signed devices will fail
        pass

    def get_version(self):
        """

python-packages/securesync/models.py
# The sub-applications have a true django application layout
# but can never be used independently from their container model which is
# also an application of its own.
# This will cause possible overlapping table prefixing and potential hardships
# for the django load time model resolver.

from .devices.models import *
from .engine.models import *

python-packages/securesync/forms.py
from .devices.forms import *

python-packages/securesync/views.py
"""
"""
from .devices.views import *

python-packages/securesync/templates/securesync/register_public_key_client.html
{% extends base_template %}
{% load i18n %}
{% load staticfiles %}

{% block register_active %}active{% endblock register_active %}

{% block title %}{% trans "Register a Device" %} {{ block.super }}{% endblock title %}

{% block headcss %}{{ block.super }}
    <style>
        #one-click-register {
            margin-top:15px;
        }
        
        #online-register {
            margin-top:15px;
        }

    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script>
        window.auto_registration_url = "{{ auto_registration_url }}";
    </script>
    <script src="{% static 'js/distributed/bundles/bundle_register_public_key_client.js' %}"></script>
{% endblock headjs %}

{% block content %}
    {% if not unregistered %}
        <h2>{% trans "Device registration" %}</h2>
    {% endif %}
    {% if error_msg %}
        {% comment %}Translators: Please do not edit the variable text: %(command)s {% endcomment %}
        <p>{% blocktrans %}Sorry, there was an error during registration.{% endblocktrans %}</p>
        <p>{% trans "The error message was:" %} <b>{{ error_msg }}</b></p>
    {% endif %}

    {% if newly_registered %}
    <p>{% trans "Congratulations, this device has now been registered." %}</p>
    {% endif %}

    {% if already_registered %}
    <p>{% trans "This device has already been registered." %}</p>
    {% endif %}

    {% if no_internet %}
    <p>{% trans "The device needs to have internet access when first being registered. Please ensure it is connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>.</p>
    {% endif %}


    {% if unregistered %}
    <div class="row">
        <h2 class="col-md-12">{% trans "What is device registration?" %}</h2>
        <p class="col-md-10" id="reg-dev-installation-info">
            {% trans "Once you register your installation with us, your data can be synced to our online repository when KA Lite has access to the Internet. This is a good thing! Here's why:" %}
        </p>
        <ul class="col-md-9 col-md-push-1 col-xs-push-1">
            <li><em>{% trans "Your data will be backed up online" %}</em></li>
            <li><em>{% trans "You can login online and review your usage data" %}</em></li>
            <li><em>{% trans "Our team can use this data to objectively assess the impact our work is having around the world!" %}</em></li>
        </ul>
    </div>

    <div class="row" id="register-online-row">
        <h2 class="col-md-12">{% trans "Ready to register? You have two options:" %}</h2>

            <div class="col-md-5" id="reg-dev-register-div">
                <h4 class="reg-dev-title-info">{% trans "One-click registration (no online access to data)" %}</h4>
                <p>
                    <strong>{% trans "The perfect option for individual users who just want to get KA Lite up and running fast and don't need online access to data." %}</strong>
                </p>
                <p>
                    {% trans "This allows you to get the registration process over in one-click without worrying about creating a login that you're never going to use." %}
                </p>
                <a class="btn btn-success" role="button" id="one-click-register" href="javascript:void(0)">
                    {% trans "One-click registration now!" %}
                </a>
            </div>

            <div class="col-md-6">
                <h4 class="reg-dev-title-info">{% trans "Register with online access to data!" %}</h4>
                <p>
                    <strong>{% trans "The perfect option for adminstrators of larger projects!" %}</strong>
                </p>
                <p>
                    {% trans "This option will walk you through the process of creating a login to our website that will allow you access your uploaded data and connect multiple installations to the same account." %}
                </p>
                <a class="btn btn-success" role="button" id="online-register" href="{{ classic_registration_url }}">
                    {% trans "Register with an online account now!" %}
                </a>
            </div>

    </div>


    {% endif %}
{% endblock content %}

python-packages/securesync/templates/securesync/register_public_key_server.html
{% extends base_template %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Register device to a sharing network" %} {{ block.super }}{% endblock title %}

{% block headjs %}
    <script type="text/javascript" src="{% static 'js/purl.js' %}"></script>
    <script>
        $(function() {
            var cururl = $.url(window.location);
            var public_key = null;
            var params = cururl.param();
            for (key in params) {
                if (key.length > 50 && cururl.param(key) == "") {
                    public_key = key;
                    break;
                } else if (params[key].length > 50) {
                    public_key = params[key];
                    break;
                }
            }
            $("#id_public_key").val(decodeURIComponent(public_key));
            $('#id_public_key').attr('readonly',true);
            $('#id_public_key').css('color','grey');
        });
    </script>
{% endblock headjs %}

{% block content %}
    <h2>{% trans "Register a device" %}</h2>
    <form method="post" class="basic-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" class="submit"/>
    </form>
{% endblock content %}