kalite/control_panel/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(__package__ + '.views',
    # Zone
    url(r'zone/(?P<zone_id>\w+)/$', 'zone_management', {}, 'zone_management'),
    url(r'zone/(?P<zone_id>\w+)/edit$', 'zone_form', {}, 'zone_form'),

    # Device
    url(r'zone/(?P<zone_id>\w+)/device/(?P<device_id>\w+)/$', 'device_management', {}, 'device_management'),

    # Facility
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/edit$', 'facility_form', {}, 'facility_form'),
    url(r'zone/(?P<zone_id>\w+)/facility/new/$', 'facility_form', {"facility_id": "new"}, 'add_facility'),
    url(r'facility/(?P<facility_id>\w+)/edit/$', 'facility_form', {}, 'facility_form'),
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/management/$', 'facility_management', {}, 'facility_management'),
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/management/group/(?P<group_id>\w+)/$', 'facility_management', {}, 'group_management'),

    url(r'account/$', 'account_management', {}, 'account_management'),
    url(r'export/$', 'data_export', {}, 'data_export'),    
)

kalite/distributed/urls.py
"""
URLS for constructing the KA Lite app. Mostly imported from other apps.
Notable urls include:
* serving media and static files.  This can be overriden by putting a (fast) front-end server
    (like nginx) to speed things up.
* The "splat" handler, which catches all uncaught requests, and tries to turn them into a
    node in the topic tree.
"""
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

from . import api_urls
import kalite.dynamic_assets.urls
import kalite.coachreports.urls
import kalite.control_panel.urls
import kalite.facility.urls
import kalite.updates.urls
import securesync.urls

from kalite.contentload import settings as contentload_settings

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^images/.*$', lambda request: HttpResponseRedirect(settings.STATIC_URL[:-1] + request.path)),
    url(r'^favico.ico/?$', lambda request: HttpResponseRedirect(settings.STATIC_URL + "images/distributed/" + request.path)),
)


urlpatterns += patterns('',
    url(r'^securesync/', include(kalite.facility.urls)),  # for backwards compat
    url(r'^securesync/', include(securesync.urls)),
)


# TODO: This should only be in DEBUG settings and the HTTP server should be
# serving it otherwise. Cherrypy is currently serving it through modifications
# in kalite/distributed/cherrypyserver.py
urlpatterns += patterns('',
    url(r'^%skhan/(?P<path>.*)$' % settings.CONTENT_URL[1:], 'django.views.static.serve', {
        'document_root': contentload_settings.KHAN_ASSESSMENT_ITEM_ROOT,
    }),
    url(r'^%s(?P<path>.*)$' % settings.CONTENT_URL[1:], 'django.views.static.serve', {
        'document_root': settings.CONTENT_ROOT,
    }),
    url(r'^%s(?P<path>.*)$' % settings.CONTENT_DATA_URL[1:], 'django.views.static.serve', {
        'document_root': settings.CONTENT_DATA_PATH,
    }),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

# Teaching / admin patterns
urlpatterns += patterns(__package__ + '.views',
    # For teachers
    url(r'^coachreports/', include(kalite.coachreports.urls)),

    # For admins
    url(r'^update/', include(kalite.updates.urls)),

    url(r'^help/$', 'help', {}, 'help'),

    # API
    url(r'^api/', include(api_urls)),

    # Management: Zone, facility, device
    url(r'^management/zone/$', 'zone_redirect', {}, 'zone_redirect'),  # only one zone, so make an easy way to access it
    url(r'^management/device/$', 'device_redirect', {}, 'device_redirect'),  # only one device, so make an easy way to access it
    url(r'^management/', include(kalite.control_panel.urls)),  # no org_id, but parameter needed for reverse url look-up
)

# Dynamic assets
urlpatterns += patterns('',
    url(r'^_generated/', include(kalite.dynamic_assets.urls)),
)

# Testing
if "kalite.testing.loadtesting" in settings.INSTALLED_APPS:
    urlpatterns += patterns(__package__ + '.views',
        url(r'^loadtesting/', include('kalite.testing.loadtesting.urls')),
    )

# Front-end
urlpatterns += patterns(__package__ + '.views',
    url(r'^$', 'homepage', {}, 'homepage'),
    url(r'^search/$', 'search', {}, 'search'),
    # the following pattern is a catch-all, so keep it last:

    # Allows remote admin of the distributed server
    url(r'^cryptologin/$', 'crypto_login', {}, 'crypto_login'),

    # the following has no "$", and thus catches anything starting with "learn/"
    url(r'^learn/', 'learn', {}, 'learn'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
    )

handler403 = __package__ + '.views.handler_403'
handler404 = __package__ + '.views.handler_404'
handler500 = __package__ + '.views.handler_500'

kalite/facility/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

from . import api_urls


urlpatterns = patterns(__package__ + '.views',
    url(r'^teacher/$', 'add_facility_teacher', {},'add_facility_teacher'),
    url(r'^student/$', 'add_facility_student', {}, 'add_facility_student'),
    url(r'^signup/$', 'facility_user_signup', {}, 'facility_user_signup'),
    url(r'^user/(?P<facility_user_id>\w+)/edit/$', 'edit_facility_user', {}, 'edit_facility_user'),

    url(r'^group/$', 'group_edit', {'group_id': 'new'}, 'add_group'),
    url(r'^group/(?P<group_id>\w+)/edit/$', 'group_edit', {'facility': None}, 'group_edit'),

   
)

urlpatterns += patterns(__package__ + '.api_views',
    url(r'^api/', include(api_urls)),
)

kalite/updates/urls.py
from django.conf.urls import patterns, url
from django.conf import settings


urlpatterns = patterns(__package__ + '.views',
    url(r'^videos/$', 'update_videos', {}, 'update_videos'),
    url(r'^languages/$', 'update_languages', {}, 'update_languages')

)

kalite/facility/models.py
"""
"""
from __future__ import absolute_import

from annoying.functions import get_object_or_None
from pbkdf2 import crypt

from django.conf import settings; logging = settings.LOG
from django.contrib.auth.models import check_password
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _

from fle_utils.config.models import Settings
from fle_utils.django_utils.users import verify_raw_password
from securesync.models import DeviceZone
from securesync.engine.models import DeferredCountSyncedModel


class Facility(DeferredCountSyncedModel):
    name = models.CharField(verbose_name=_("Name"), help_text=_("(This is the name that learners/coaches will see when choosing their facility; it can be in the local language.)"), max_length=100)
    description = models.TextField(blank=True, verbose_name=_("Description"))
    address = models.CharField(verbose_name=_("Address"), help_text=_("(Please provide as detailed an address as possible.)"), max_length=400, blank=True)
    address_normalized = models.CharField(max_length=400, blank=True)
    latitude = models.FloatField(blank=True, verbose_name=_("Latitude"), null=True)
    longitude = models.FloatField(blank=True, verbose_name=_("Longitude"), null=True)
    zoom = models.FloatField(blank=True, verbose_name=_("Zoom"), null=True)
    contact_name = models.CharField(verbose_name=_("Contact Name"), help_text=_("(Who should we contact with any questions about this facility?)"), max_length=60, blank=True)
    contact_phone = models.CharField(max_length=60, verbose_name=_("Contact Phone"), blank=True)
    contact_email = models.EmailField(max_length=60, verbose_name=_("Contact Email"), blank=True)
    user_count = models.IntegerField(verbose_name=_("User Count"), help_text=_("(How many potential users do you estimate there are at this facility?)"), blank=True, null=True)

    class Meta:
        verbose_name_plural = _("Facilities")
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        if not self.id:
            return self.name
        return u"%s (#%s)" % (self.name, int(self.id[:3], 16))

    def is_default(self):
        return self.id == Settings.get("default_facility")

    @classmethod
    def from_zone(cls, zone):
        """Our best approximation of how to map facilities to zones"""

        facilities = set(Facility.objects.filter(zone_fallback=zone))

        for device_zone in DeviceZone.objects.filter(zone=zone):
            device = device_zone.device
            facilities = facilities.union(set(Facility.objects.filter(signed_by=device)))

        return facilities

    @classmethod
    def initialize_default_facility(cls, facility_name=None):
        facility_name = facility_name or getattr(settings, "INSTALL_FACILITY_NAME", None) or unicode(_("Default Facility"))

        # Finally, install a facility--would help users get off the ground
        facilities = Facility.objects.filter(name=facility_name)
        if facilities.count() == 0:
            # Create a facility, set it as the default.
            facility = Facility(name=facility_name)
            facility.save()
            Settings.set("default_facility", facility.id)

        elif Settings.get("default_facility") not in [fac.id for fac in facilities.all()]:
            # Use an existing facility as the default, if one of them isn't the default already.
            Settings.set("default_facility", facilities[0].id)

    @property
    def has_ungrouped_students(self):
        """
        Checks if this facility has ungrouped students or not.
        """
        return len(FacilityUser.objects.filter(facility=self, is_teacher=False, group__isnull=True)) > 0


class FacilityGroup(DeferredCountSyncedModel):
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    name = models.CharField(max_length=30, verbose_name=_("Name"))
    description = models.TextField(blank=True, verbose_name=_("Description")); description.minversion = "0.13.0"

    def __init__(self, *args, **kwargs):
        super(FacilityGroup, self).__init__(*args, **kwargs)
        self._unhashable_fields += ("description",) # since it's being stripped out by minversion, we can't include it in the signature

    class Meta:
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return self.name

    @transaction.commit_on_success
    def soft_delete(self):
        """
        As FacilityGroup acts as a soft wrapper around FacilityUser entities, upon soft deletion
        we 'evict' the FacilityUsers rather than the default behaviour of soft deleting all the
        entities that ForeignKey onto the object. As such, we completely overwrite the super
        soft_delete method.
        """

        self.deleted = True  # mark self as deleted

        # This is not very robust, as it relies on explicitly calling the reverse relations to the model
        # and then clearing them. If anything else Foreign Keys onto groups here, it will have to be set here.
        # Note that we cannot simply call .clear() on the reverse relation, as then the user models are not signed.
        for user in self.facilityuser_set.all():
            user.group = None
            user.save()

        self.save()

    def get_zone(self, *args, **kwargs):
        zone = super(FacilityGroup, self).get_zone(*args, **kwargs)

        # if we don't have a zone based on signed_by or zone_fallback, use zone of associated Facility
        if not zone:
            zone = self.facility.get_zone()

        return zone

    @property
    def title(self):
        if self.description:
            return "%s - %s" % (self.name, self.description,)
        return self.name


class FacilityUser(DeferredCountSyncedModel):
    # Translators: This is a label in a form.
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    # Translators: This is a label in a form.
    group = models.ForeignKey(FacilityGroup, verbose_name=_("(Group/class)"), blank=True, null=True, help_text=_("(optional)"))
    # Translators: This is a label in a form.
    username = models.CharField(max_length=30, verbose_name=_("Username"))
    # Translators: This is a label in a form.
    first_name = models.CharField(max_length=30, verbose_name=_("First Name"), blank=True)
    # Translators: This is a label in a form.
    last_name = models.CharField(max_length=60, verbose_name=_("Last Name"), blank=True)
    # Translators: This is a label in a form.
    is_teacher = models.BooleanField(default=False, help_text=_("(whether this user should have coach permissions)"))
    notes = models.TextField(blank=True)
    password = models.CharField(max_length=128)
    default_language = models.CharField(max_length=8, blank=True, null=True); default_language.minversion="0.11.1"

    class Meta:
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return u"%s (Facility: %s)" % (self.get_name(), self.facility)

    def save(self, *args, **kwargs):
        """
        Validate password format before saving
        """
        # Now, validate password.
        if self.password.split("$", 1)[0] == "sha1":
            # Django's built-in password checker for SHA1-hashed passwords
            pass
        elif len(self.password.split("$", 2)) == 3 and self.password.split("$", 2)[1] == "p5k2":
            # PBKDF2 password checking
            # Could fail if password doesn't split into parts nicely
            pass
        elif self.password is not None:
            raise ValidationError(_("Unknown password format."))
        else:
            raise ValidationError(_("Call set_password before saving the user."))

        # Now, validate group:
        if self.group and self.facility and self.group.facility != self.facility:
            raise ValidationError(_("Facility group must be in the same facility as the user."))

        super(FacilityUser, self).save(*args, **kwargs)

        # in case the password was changed on another server, and then synced into here, clear cached password
        CachedPassword.invalidate_cached_password(user=self)

    def check_password(self, raw_password):
        cached_password = CachedPassword.get_cached_password(self)
        cur_password = cached_password or self.password

        # Check the password
        if cur_password.split("$", 1)[0] == "sha1":
            # use Django's built-in password checker for SHA1-hashed passwords
            okie_dokie = check_password(raw_password, cur_password)
        elif cur_password.split("$", 2)[1] == "p5k2":
            # use PBKDF2 password checking
            okie_dokie = cur_password == crypt(raw_password, cur_password)
        else:
            raise ValidationError(_("Unknown password format."))

        # Update on cached password-relevant stuff
        if okie_dokie and not cached_password and self.id:  # only can create if the user's been saved
            CachedPassword.set_cached_password(self, raw_password=raw_password)

        return okie_dokie

    def set_password(self, raw_password=None, hashed_password=None, cached_password=None):
        """Set a password with the raw password string, or the pre-hashed password.
        If using the raw string, """
        assert hashed_password is None or settings.DEBUG, "Only use hashed_password in debug mode."
        assert raw_password is not None or hashed_password is not None, "Must be passing in raw or hashed password"
        assert not (raw_password is not None and hashed_password is not None), "Must be specifying only one--not both."

        if raw_password:
            verify_raw_password(raw_password)

        if hashed_password:
            self.password = hashed_password

            # Can't save a cached password from a hash, so just make sure there is none.

kalite/control_panel/forms.py
from django import forms
from django.forms import ModelForm

from securesync.models import Zone


class ZoneForm(ModelForm):
    class Meta:
        model = Zone
        fields = ('name', 'description')

class UploadFileForm(forms.Form):
    file  = forms.FileField()

class DateRangeForm(forms.Form):
    """Form that validates Dates for CSV Export"""

    period_start = forms.DateField()
    period_end = forms.DateField()

kalite/control_panel/templates/control_panel/account_management.html
{% extends "control_panel/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load my_filters %}
{% load include_block %}

{% block i18n_do_not_translate %}
    {% block username_active %}active{% endblock username_active %}
    {% block control_panel_active %}{% endblock control_panel_active %}
    {% block progress_active %}active{% endblock progress_active %}
    {% block account_management_active %}active{% endblock account_management_active %}
{% endblock i18n_do_not_translate %}
        
{% block title %}{{ student.get_name }} - {% trans "User Management" %}{{ block.super }}{% endblock title%}

{% block headjs %}
    {% include_block "coachreports/student_view.html" "student_report_js" %}    
{% endblock headjs %}

{% block headcss %}{% comment %}Don't insert block.super here, because block.super is WEIRD and isn't the super for student_view IN student view, but instead THIS super.{% endcomment %}
    {% include_block "coachreports/student_view.html" "headcss" %}
{% endblock headcss %}


{% block titlebar_title %}
    <div class="container">
        
        <div class="row">
            <li id="account-management-page-title">
                {% blocktrans with student_name=student.get_name %}Account management page for {{ student_name }}{% endblocktrans %}
            </li>
        {% endblock titlebar_title %}

        {% block buttons %}
            {% if not is_central %}
                {% if not restricted %}
                <li>
                    <a class="btn btn-success" role="button" href="{% url 'edit_facility_user' id=student.id %}?next={{ request.path }}">{% trans "Edit account preferences" %}</a>
                </li>
                {% endif %}
                <li class="client-online-only">
                    <a class="server-online-only btn btn-success" role="button" href="{% url 'update_all_distributed' %}">{% trans "Download data from Khan Academy" %}</a>
                </li>
        </div>
    
    </div>
    {% endif %}
{% endblock buttons %}

{% block content %}
    {% block titlebar %}{{ block.super }}
    {% endblock titlebar %}

    {% include_block "coachreports/student_view.html" "student_report" %}
{% endblock content %}

kalite/control_panel/templates/control_panel/base.html
{% extends base_template %}
{% load staticfiles %}
{% load i18n %}

{% block headjs %}{{ block.super }}
<script type="text/javascript">
    window.ZONE_ID = "{{ zone_id }}";
    {% for id, device in devices.items %}
        {% if device.is_own_device %}
            window.DEVICE_ID = "{{ id }}";
        {% endif %}
    {% endfor %}
</script>
{% endblock headjs %}

{% block headcss %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/control_panel/base.css' %}" />
    <!-- Override bootstrap here to fix up search bar -->
    <style type="text/css">
        .container {
            max-width: 1030px;
        }
        ul.pagination {
            margin: 0px;
        }
        ul.pagination > .active > a {
            color: #ffffff;
        }
    </style>
{% endblock headcss %}

{% block content %}

{% block subnavbar %}{{block.super}}{% endblock subnavbar %}

    {% block titlebar %}
        <ul class="titlebar__title">
        {% block titlebar_title %}
            {% comment "Draw the top navigation bar" %}{% endcomment %}
            {% if org %}
            <li><a href="{% url 'org_management' %}">{{ org.name }}</a></li>
            {% endif %}

            <li>
                {% if org %}/{% endif %}
                {% if facility or device %}<a href="{% url 'zone_management' zone_id=zone_id %}">{% endif %}
                    {% if is_headless_zone %}
                        {% trans "Local KA Lite Installation" %}
                    {% elif zone %}
                        {{ zone.name|truncatechars:35 }}
                    {% elif not zone %}
                        {% if is_central %}
                        {% trans "New Sharing Network" %}
                        {% else %}
                            {% trans "Unregistered Device" %} {{ device.name }} - <a class="not-registered-only" href="{% url 'register_public_key' %}">{% trans "Register Now!" %}</a>
                        {% endif %}
                    {% endif %}
                {% if facility or device %}</a>
                {% elif own_device_is_trusted %}
                <a class="edit-link" href="{% url 'zone_form' zone_id=zone_id %}">
                    <span aria-hidden="true"><i class="glyphicon glyphicon-pencil" title="{% trans 'Edit' %}"></i></span>
                    <span class="sr-only">{% trans 'Edit' %}</span>
                </a>
                {% endif %}
            </li>
            <li>

            {% if device %}
            <li>/ {% if device.name %}{{ device.name }}{% else %}{{ device.id }}{% endif %}</li>
            {% endif %}

            {% if facility %}
            <li>
                / {% if group_id %}<a href="{% url 'facility_management' zone_id=zone_id facility_id=facility_id %}">{{ facility.name }}</a>
                {% else %}
                {{ facility.name }}
                <a class="edit-link edit-facility" href="{% url 'facility_form' zone_id=zone_id facility_id=facility.id %}">
                    <span aria-hidden="true"><i class="glyphicon glyphicon-pencil" title="{% trans 'Edit' %}"></i></span>
                    <span class="sr-only">{% trans 'Edit' %}</span>
                </a>
                {% endif %}
            </li>
            {% endif %}

            {% if group %}
            <li>{% if facility %}/ {% endif %}{{ group.name }}</li>

            {% endif %}
        {% endblock titlebar_title %}
            {% comment "Provide upload/download buttons; each button should be an LI" %}{% endcomment %}
            {% comment "Provide upload/download buttons; each button should be an LI" %}{% endcomment %}
            <ul class="pull-right">
            {% block buttons %}
            {% endblock buttons %}
            </ul>
        </ul>
    {% endblock titlebar %}

    {% block control_panel_content %}
    {% endblock control_panel_content %}
{% endblock content %}

kalite/control_panel/templates/control_panel/base_printable.html
{% extends "control_panel/base.html" %}
{% load i18n %}

{% block buttons %}{{ block.super }}
    <!--li>
        <a class="btn btn-success" role="button" href="javascript:alert('NYI; sorry!');">{% trans "Print Report" %}</a>
    </li-->
{% endblock buttons %}
{% block manage_nav %}{{  block.super }}{% endblock manage_nav %}

kalite/control_panel/templates/control_panel/facility.html
{% extends "control_panel/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
    {% if form.instance.id %}
        {% trans "Edit" %}
    {% else %}
        {% trans "Add" %}
    {% endif %}
    {% trans "Facility" %}
{% endblock title %}

{% block headcss %}
{{ block.super }}
    <style>
        #map_canvas {
            display: none;
            margin-bottom: 30px;
            width: 100%;
            height: 400px
        }
        #search-panel {
            width: 550px;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            margin-bottom: 10px;
            border: 1px solid #999;
        }
        #search-panel input {
            font-size: 12px;
            width: 100%;
        }
        #target {
            width: 545px;
        }
        span.helptext {
            margin-top: 5px;
        }
        #id_name {
            width: 300px;
        }
        #id_address {
            width: 500px;
        }
        #id_latitude, #id_longitude {
            width: 150px;
        }
        #id_direc_map {
            display: none;
            padding-bottom: 10px;
            font-size: 14px;
        }
        #id_direc_no_map {
            padding-bottom: 10px;
            font-size: 14px;
        }
        @media only screen and (max-width: 596px) {
            #search-panel { width: 100%; }
        }
        @media only screen and (max-width: 532px) {
            #search-panel { border: none; padding: 0; }
            #search-panel input { font-size: 8.5px; }
            #id_address { width: 100%; }
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUVMGp6Uks8OCczFfrWo20zHnmENyW5O0&v=3.9&sensor=false&libraries=places"></script>
    <script type="text/javascript">
        $(function() {
            $('#id_address_normalized').parent().hide();
            $('#id_zoom').parent().hide();
            $('#id_latitude').parent().hide();
            $('#id_longitude').parent().hide();
        });

        function displayFormLatLng(map, marker) {
            var longitude = $("#id_longitude").val();
            var latitude = $("#id_latitude").val();
            if (longitude && latitude) {
                var latLng = new google.maps.LatLng(latitude, longitude);
                map.setCenter(latLng);
                marker.setPosition(latLng);
                marker.setVisible(true);
            }
        }


        function saveLatLng(lat, lon) {
            $("#id_latitude").val(lat);
            $("#id_longitude").val(lon);
        }

        function getAddress(ad) {
            $("#id_address_normalized").val(ad);
        }

        function saveZoom(zm) {
            $("#id_zoom").val(zm);
        }

        function initialize()
        {
            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                mapTypeId: google.maps.MapTypeId.SATELLITE,
                scrollwheel: false,
                maxZoom: 20,
                minZoom: 3,
            });
            var defaultBounds = new google.maps.LatLngBounds(
                new google.maps.LatLng(-33.8902, 151.1759),
                new google.maps.LatLng(-33.8474, 151.2631));
            map.fitBounds(defaultBounds);

            var input = document.getElementById('target');
            var searchBox = new google.maps.places.Autocomplete(input);

            var myLatLng = new google.maps.LatLng(-33.8902, 151.1759);

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                draggable: true,
                visible: false,
                clickable: true,
            });

            saveZoom(map.getZoom());

            google.maps.event.addListener(map, 'click', function(ev) {
                    marker.setVisible(true);
                    marker.setPosition(ev.latLng);
                    saveLatLng(ev.latLng.lat(), ev.latLng.lng());
            });


            google.maps.event.addListener(searchBox, 'place_changed', function() {
                var place = searchBox.getPlace();
                var bounds = new google.maps.LatLngBounds();

                marker.setVisible(true);
                marker.setPosition(place.geometry.location);
                bounds.extend(place.geometry.location);
                saveLatLng(place.geometry.location.lat(), place.geometry.location.lng());
                getAddress(place.formatted_address);
                // if a place has a geometry, display it on the map
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                    marker.setPosition(place.geometry.viewport);
                }
                else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(13);
                }
            });

            $('#map_canvas').show();
            $('#id_direc_no_map').hide();
            $('#id_direc_map').show();
            google.maps.event.addListenerOnce(map, 'idle', function() {
                displayFormLatLng(map, marker);
            });

            google.maps.event.addListener(map, 'zoom_changed', function(){
                saveZoom(map.getZoom());
            });
        }

        if (window.google) {
            google.maps.event.addDomListener(window, 'load', initialize);
        }
    </script>
{% endblock headjs %}

{% block content %}

    {{ block.super }}

 
    <h3 class="no-margin-top">{% if form.instance.id %}{% trans "Edit a facility" %}{% else %}{% trans "Add a new Facility" %}{% endif %}</h3>
    <div id="id_direc_no_map">{% trans "Please enter the following information about your facility. Please enter a detailed address, because knowing where you are in the world allows us to better plan for future deployments and partnerships." %}</div>
    <div id="id_direc_map">
        {% trans "Please use this search box to locate your facility (and/or click on the map to select a spot), and then enter the additional information in the form below." %}<br/>
        {% trans "(Knowing, as closely as possible, where you are in the world allows us to better plan for future deployments and partnerships)" %}
    </div>
    <div id="search-panel">
        {% trans "Search for your facility's address or name to find its location on the map (enter to search)" as placeholder %}
        <input id="target" type="text" placeholder="{{placeholder}}">
    </div>
    <div id="map_canvas"></div>
    <form id="facility_form" method="post" class="basic-form">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                <span class="helptext">{{ field.help_text }}</span>
            </p>
        {% endfor %}
        {% trans "Save facility" as value %}
        <input type="submit" value="{{ value }}" class="submit btn btn-default btn-sm"/>
    </form>
{% endblock content %}

kalite/control_panel/templates/control_panel/zone_form.html
{% extends "control_panel/base.html" %}
{% load i18n %}

{% block title %}{% if zone.name %}{{ zone.name }} - {% endif %}{% trans "Sharing Network Add / Edit" %}{% endblock title %}

{% block control_panel_content %}
<div id="zone_container">
    <form method="post" class="basic-form">
    {% csrf_token %}

    <div>
        <h2>
            {% if form.instance.pk %}{% trans "Update Your Sharing Network" %}{% else %}{% trans "Create A Sharing Network" %}{% endif %}
            <span class="glossary-link nudge-left" title="{% trans "A 'Sharing Network' is a set of KA Lite installations that share logins and learner progress with each other through the internet (when available)." %}"></span>
        </h2>

        {{ form.as_p }}

        {% if form.instance.pk %}
        <input type="submit" value="{% trans 'Update Sharing Network' %}" class="button"/>
        {% else %}
        <input type="submit" value="{% trans 'Create Sharing Network' %}" class="button"/>
        {% endif %}
    </div>
    </form>
</div>
{% endblock control_panel_content %}